FROM {{.Repository}}/{{.Framework}}-{{.Genre}}:{{.Os}}

MAINTAINER Aaron liu "254311953@qq.com"

RUN mkdir -p {{.Workpath}}:
COPY ./ {{.Workpath}}
COPY {{.Scriptpath}}  {{.PodScriptpath}}

RUN chmod a+x {{.PodScriptpath}} 
ENTRYPOINT [{{.PodScriptpath}}]
