TeamInfo:
  TeamID: 001
  TeamName: liucaihong
ProjectInfo:
  ProjectVersion: v1
  DataVersion: v1
  ProjectType: facerecognition
  WorkPath: /user/lib/golang/src/github.com/liuchjlu/stokis/test
  ScriptPath: /user/lib/golang/src/github.com/liuchjlu/stokis/test/start.sh
  ResultPath: /result
  OS: centos7
Frame:
  FrameType: tensorflow
  ComputeType: gpu
  WorkerNums: 1
  PsNums: 1
